defmodule Odb2Server.Codes do

  require Logger

  def info_for_code(code) when is_atom(code) do
    case Map.get(codes, code, :not_found) do
      :not_found ->
        Logger.warn("Code #{code}, not found in codes")
      message ->
        [code, " :: ", message]
    end
  end

  def info_for_code(code), do: Logger.warn("#{inspect(code)} is not an atom in the form of :P0XXX")

  def codes() do
    %{
      P0031: "Front oxygen (A/F) sensor heater circuit low input",
      P0032: "Front oxygen (A/F) sensor heater circuit high input",
      P0037: "Rear oxygen sensor heater circuit malfunction",
      P0038: "Rear oxygen sensor heater circuit high input",
      P0065: "Air assist injector solenoid valve malfunction",
      P0066: "Air assist injector solenoid valve circuit low input",
      P0067: "Air assist injector solenoid valve circuit high input",
      P0100: "Mass Air Flow Sensor Circuit Malfunction",
      P0101: "Mass Air Flow Sensor Circuit Range Problem",
      P0102: "Mass Air Flow Sensor Circuit Low Input",
      P0103: "Mass Air Flow Sensor Circuit High Input",
      P0105: "Pressure Sensor Circuit Malfunction",
      P0106: "Pressure Sensor Circuit Range Problem",
      P0107: "Pressure Sensor Circuit Low Input",
      P0108: "Pressure Sensor Circuit High Input",
      P0111: "Intake air temperature sensor circuit range/performance problem",
      P0112: "Intake air temperature sensor circuit low input",
      P0113: "Intake air temperature sensor circuit high input",
      P0115: "Engine Coolant Temperature Sensor Circuit",
      P0116: "Engine Coolant Temp Sensor Circuit Low Input",
      P0117: "Engine Coolant Temp Sensor Circuit Low Input",
      P0118: "Engine Coolant Temp Sensor Circuit High Input",
      P0120: "Throttle Position Sensor Circuit Malfunction",
      P0121: "Throttle Position Sensor Circuit Range Problem",
      P0122: "Throttle Position Sensor Circuit Range Problem",
      P0123: "Throttle Position Sensor Circuit High Input",
      P0125: "Insufficient Coolant Temperature for Closed Loop",
      P0128: "Thermostat malfunction",
      P0130: "Front Oxygen Sensor Circuit Malfunction",
      P0131: "Front oxygen (A/F) sensor circuit range/performance problem (low input)",
      P0132: "Front oxygen (A/F) sensor circuit range/performance problem (high input)",
      P0133: "Front Oxygen Sensor Circuit Slow Response",
      P0135: "Front Oxygen Sensor Heater Circuit Malfunction",
      P0136: "Rear Oxygen Sensor Circuit Malfunction",
      P0139: "Rear Oxygen Sensor Circuit Slow Response",
      P0141: "Rear Oxygen Sensor Heater Circuit Malfunction",
      P0170: "Fuel Trim Malfunction",
      P0171: "Fuel trim malfunction (A/F too lean)",
      P0172: "Fuel trim malfunction (A/F too rich)",
      P0181: "Fuel Temperature Sensor A Range Problem",
      P0182: "Fuel Temperature Sensor A Circuit Low Input",
      P0183: "Fuel Temperature Sensor A Circuit High Input",
      P0201: "Fuel Injector Circuit Malfunction – #1",
      P0202: "Fuel Injector Circuit Malfunction – #2",
      P0203: "Fuel Injector Circuit Malfunction – #3",
      P0204: "Fuel Injector Circuit Malfunction – #4",
      P0244: "Wastegate control solenoid valve malfunction (high input)",
      P0245: "Wastegate control solenoid valve circuit low input",
      P0246: "Wastegate control solenoid valve circuit high input",
      P0261: "Fuel Injector Circuit Low Input – #1",
      P0262: "Fuel Injector Circuit High Input – #1",
      P0264: "Fuel Injector Circuit Low Input – #2",
      P0265: "Fuel Injector Circuit High Input – #2",
      P0267: "Fuel Injector Circuit Low Input – #3",
      P0268: "Fuel Injector Circuit High Input – #3",
      P0270: "Fuel Injector Circuit Low Input – #4",
      P0271: "Fuel Injector Circuit High Input – #4",
      P0301: "Cylinder 1 Misfire Detected",
      P0302: "Cylinder 2 Misfire Detected",
      P0303: "Cylinder 3 Misfire Detected",
      P0304: "Cylinder 4 Misfire Detected",
      P0325: "Knock Sensor Circuit Malfunction",
      P0327: "Knock sensor circuit low input",
      P0328: "Knock sensor circuit high input",
      P0335: "Crankshaft Position Sensor Circuit Malfunction",
      P0336: "Crankshaft Position Sensor Circuit Range Problem",
      P0340: "Camshaft Position Sensor Circuit Malfunction",
      P0341: "Camshaft Position Sensor Circuit Range Problem",
      P0400: "Exhaust Gas Recirculation Flow Malfunction",
      P0403: "Exhaust Gas Recirculation Circuit Malfunction",
      P0420: "Catalyst System Efficiency Below Threshold",
      P0440: "Evaporative Emission Control System Malfunction",
      P0441: "Evap System Incorrect Purge Flow",
      P0442: "Evaporative emission control system malfunction",
      P0443: "Evap System Purge Control Valve Circuit",
      P0443: "EVAP System Purge Control Valve Circuit Low Input",
      P0444: "Evaporative emission control system purge control valve circuit low input",
      P0445: "Evaporative emission control system purge control valve circuit high input",
      P0446: "EVAP System Vent Control Low Input",
      P0447: "Evaporative emission control system vent control low input",
      P0448: "Evaporative emission control system vent control high input",
      P0451: "EVAP Pressure Sensor Range Problem",
      P0452: "EVAP Pressure Sensor Low Input",
      P0453: "EVAP Pressure Sensor High Input",
      P0456: "Evaporative emission control system malfunction",
      P0461: "Fuel Level Sensor Circuit Range/Performance Problem",
      P0462: "Fuel Level Sensor Circuit Low Input",
      P0463: "Fuel Level Sensor Circuit High Input",
      P0464: "Fuel level sensor intermittent input",
      P0480: "Cooling Fan Relay 1 Circuit Low Input",
      P0483: "Cooling Fan Function Problem",
      P0500: "Vehicle Speed Sensor Malfunction",
      P0505: "Idle Control System Malfunction",
      P0506: "Idle Control System RPM Lower Than Expected",
      P0507: "Idle Control System RPM Higher Than Expected",
      P0509: "Idle control system circuit high input",
      P0512: "Starter switch circuit high input",
      P0545: "Exhaust gas temperature sensor circuit low input",
      P0546: "Exhaust gas temperature sensor circuit high input",
      P0600: "Serial Communication Link Malfunction",
      P0601: "Internal Control Module Memory Checksum Error",
      P0604: "Internal control module memory check sum error",
      P0703: "Brake Switch Input Malfunction",
      P0705: "Transmission Range Sensor Circuit Malfunction",
      P0710: "Transmission Fluid Temperature Sensor Circuit",
      P0715: "Torque Converter Turbine Speed Sensor Circuit Malfunction",
      P0720: "Output Speed Sensor Circuit Malfunction",
      P0725: "Engine Speed Input Circuit Malfunction",
      P0731: "Gear 1 Incorrect Ratio",
      P0732: "Gear 2 Incorrect Ratio",
      P0733: "Gear 3 Incorrect Ratio",
      P0734: "Gear 4 Incorrect Ratio",
      P0740: "Torque Converter Clutch System Malfunction",
      P0741: "Torque converter clutch system malfunction",
      P0743: "Torque Converter Clutch System Electrical",
      P0748: "Pressure Control Solenoid Electrical",
      P0753: "Shift Solenoid A Electrical",
      P0758: "Shift Solenoid B Electrical",
      P0760: "Shift Solenoid C Malfunction",
      P0763: "Shift Solenoid C Electrical",
      P0778: "2-4 brake pressure control solenoid valve (2-4 brake duty solenoid) circuit malfunction",
      P0785: "2-4 brake timing control solenoid valve (2-4 brake timing solenoid) circuit malfunction",
      P1086: "Tumble generator valve #2 (LH) position sensor circuit low input",
      P1087: "Tumble generator valve #2 (LH) position sensor circuit high input",
      P1088: "Tumble generator valve #1 (RH) position sensor circuit low input",
      P1089: "Tumble generator valve #1 (RH) position sensor circuit high input",
      P1090: "Tumble generator valve #1 (RH) malfunction (stuck open)",
      P1091: "Tumble generator valve #1 (RH) malfunction (stuck close)",
      P1092: "Tumble generator valve #2 (LH) malfunction (stuck open)",
      P1093: "Tumble generator valve #2 (LH) malfunction (stuck close)",
      P1094: "Tumble generator valve circuit #1 (open circuit)",
      P1095: "Tumble generator valve circuit #1 (over current)",
      P1096: "Tumble generator valve circuit #2 (open circuit)",
      P1097: "Tumble generator valve circuit #2 (over current)",
      P1100: "Starter Switch Circuit Malfunction",
      P1101: "Neutral Position Switch Circuit High Input (A/T)",
      P1101: "Neutral Position Switch Circuit Malfunction (M/T)",
      P1102: "Pressure Sources Solenoid Valve Circuit Malfunction",
      P1103: "Pressure Sources Switching Solenoid Valve Circuit",
      P1104: "Engine Torque Control Signal Circuit Malfunction",
      P1106: "Engine Torque Control Signal 2 Circuit Malfunction",
      P1110: "Atmospheric pressure sensor low input",
      P1111: "Atmospheric pressure sensor high input",
      P1112: "Atmospheric pressure sensor range/performance problem",
      P1115: "Engine Torque Control Cut Signal Circuit High Input",
      P1116: "Engine Torque Control Cut Signal Circuit Low Input",
      P1120: "Starter Switch High Input",
      P1121: "Neutral Position Switch Circuit High Input [MT Vehicles]",
      P1121: "Neutral Position Switch Circuit Low Input [AT Vehicles]",
      P1122: "Pressure Sources Switching Valve Circuit High Input",
      P1124: "TCS Signal Circuit High Input",
      P1130: "Front oxygen sensor circuit malfunction (open circuit)",
      P1131: "Front oxygen sensor circuit malfunction (short circuit)",
      P1134: "Front oxygen (A/F) sensor microcomputer problem",
      P1137: "Front oxygen (A/F) sensor circuit range/performance problem",
      P1139: "Front oxygen (A/F) sensor #1 heater circuit performance/range problem",
      P1141: "Mass Air Flow Sensor Circuit High Input",
      P1142: "Mass Air Flow Sensor Circuit Low Input",
      P1143: "Pressure Sensor Circuit Low Input",
      P1144: "Pressure Sensor Circuit High Input",
      P1146: "Pressure sensor circuit range/performance problem (high input)",
      P1150: "Front Oxygen Sensor Heater Circuit High Input",
      P1151: "Rear Oxygen Sensor Heater Circuit High Input",
      P1230: "Fuel pump control unit malfunction",
      P1244: "Wastegate control solenoid valve malfunction (low input)",
      P1245: "Wastegate control solenoid valve malfunction (fail-safe)",
      P1301: "Fire due to increased exhaust temperature",
      P1312: "Exhaust temperature sensor malfunction",
      P1325: "Knock Sensor Circuit Low Input",
      P1400: "Fuel Tank Pressure Control Solenoid Low Input",
      P1420: "Fuel Tank Pressure Control Solenoid High Input",
      P1421: "Exhaust Gas Recirculation Circuit High Input",
      P1422: "EVAP Purge Control Valve Circuit High Input",
      P1423: "EVAP Vent Control High Input",
      P1440: "Fuel Tank Pressure Control System Low Input",
      P1441: "Fuel Tank Pressure Control System High Input",
      P1442: "Fuel Level Sensor Circuit Range/Perf",
      P1443: "EVAP Control System Vent Control Function Problem",
      P1480: "Cooling fan relay 1 circuit high input",
      P1500: "Radiator Fan Relay 1 Circuit Malfunction",
      P1501: "Idle Control System Malfunction (Fail Safe)",
      P1502: "Radiator Fan Function Problem",
      P1507: "Idle Control System Malfunction (Fail Safe)",
      P1510: "Idle Air Control Solenoid Signal 1 Circuit Low Input",
      P1511: "Idle Air Control Solenoid Signal 1 Circuit High Input",
      P1512: "Idle Air Control Solenoid Signal 2 Circuit Low Input",
      P1513: "Idle Air Control Solenoid Signal 2 Circuit High Input",
      P1514: "Idle Air Control Solenoid Signal 3 Circuit Low Input",
      P1515: "Idle Air Control Solenoid Signal 3 Circuit High Input",
      P1516: "Idle Air Control Solenoid Signal 4 Circuit Low Input",
      P1517: "Idle Air Control Solenoid Signal 4 Circuit High Input",
      P1518: "Starter switch circuit low input",
      P1520: "Radiator Fan Relay 1 Circuit High Input",
      P1540: "Vehicle Speed Sensor Malfunction 2",
      P1544: "High exhaust temperature detected",
      P1560: "Back-Up Voltage Circuit Malfunction",
      P1590: "Neutral position switch circuit high input",
      P1591: "Neutral position switch circuit low input",
      P1592: "Neutral position switch circuit (MT model)",
      P1594: "Automatic transmission diagnosis input signal circuit malfunction",
      P1595: "Automatic transmission diagnosis input signal circuit low input",
      P1596: "Automatic transmission diagnosis input signal circuit high input",
      P1698: "Engine torque control cut signal circuit low input",
      P1699: "Engine torque control cut signal circuit high input",
      P1700: "Throttle Position Sensor Circuit Malfunction (A/T)",
      P1701: "Cruise Control Set Signal Circuit Malfunction (A/T)",
      P1702: "Auto Trans Diagnosis Input Signal Circuit",
      P1703: "Low clutch timing control solenoid valve circuit malfunction",
      P1704: "2-4 Brake Timing Solenoid Valve Circuit Malfunction",
      P1705: "2-4 Brake Pressure Solenoid Valve (Solenoid D) Circuit",
      P1711: "Engine torque control signal 1 circuit malfunction",
      P1712: "Engine torque control signal 2 circuit malfunction",
      P1722: "Auto Trans Diagnosis Input Signal High Input",
      P1742: "Auto Trans Diagnosis Input Signal Malfunction"
    }
  end
end
